name: Fetch playlist

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  fetch-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download NS_player.m3u (raw m3u)
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl -sL "$API_URL" -o NS_player.m3u

      - name: Download JSON and convert to ott_navigator.m3u
        env:
          JSON_URL: ${{ secrets.API_URL }}
        run: |
          echo "#EXTM3U" > ott_navigator.m3u

          curl -sL "$JSON_URL" | jq -c '.[]' | while read -r item; do
            name=$(echo "$item" | jq -r '.name')
            logo=$(echo "$item" | jq -r '.logo')
            link=$(echo "$item" | jq -r '.link')
            cookie=$(echo "$item" | jq -r '.cookie')

            echo "#EXTINF:-1 group-title=\"LIVE\" tvg-chno=\"\" tvg-id=\"\" tvg-logo=\"$logo\", $name" >> ott_navigator.m3u
            echo "#EXTVLCOPT:http-user-agent=Toffee (Linux;Android 14) AndroidXMedia3/1.1.1/64103898/4d2ec9b8c7534adc" >> ott_navigator.m3u
            echo "#EXTHTTP:{\"cookie\":\"$cookie\"}" >> ott_navigator.m3u
            echo "$link" >> ott_navigator.m3u
          done

      - name: Commit and push if any changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add NS_player.m3u ott_navigator.m3u
            git commit -m "Update playlists [$(date '+%Y-%m-%d %H:%M:%S')]"
            git push
          else
            echo "No changes detected."
          fi
